export const mockMovieResults = [
  {
    adult: false,
    backdrop_path: '/nq4LRhGrCZ8ucxMaLMPa3uZV6ku.jpg',
    genre_ids: [35],
    id: 709629,
    original_language: 'es',
    original_title: 'Guerra de Likes',
    overview:
      'In order to advance her career in the dynamic world of publicity in Mexico City, Raquel tries to reunite with her high school friend Cecy who has become the queen of social media. But unlike followers, friendships do not come instantly.',
    popularity: 359.652,
    poster_path: '/jpdWHOu6EJbYnLXLCA52h82nLEz.jpg',
    release_date: '2021-03-12',
    title: 'War of Likes',
    video: false,
    vote_average: 7.9,
    vote_count: 193,
  },
  {
    adult: false,
    backdrop_path: '/las0P4Dua54XrZ73VQmGUaH1z0U.jpg',
    genre_ids: [16, 28, 18, 878],
    id: 283566,
    original_language: 'ja',
    original_title: 'シン・エヴァンゲリオン劇場版:||',
    overview:
      'In the aftermath of the Fourth Impact, stranded without their Evangelions, Shinji, Asuka, and Rei search for refuge in the desolate red remains of Tokyo-3. But the danger to the world is far from over. A new impact is looming on the horizon—one that will prove to be the true end of Evangelion.',
    popularity: 353.809,
    poster_path: '/jDwZavHo99JtGsCyRzp4epeeBHx.jpg',
    release_date: '2021-03-08',
    title: 'Evangelion: 3.0+1.0 Thrice Upon a Time',
    video: false,
    vote_average: 6.5,
    vote_count: 6,
  },
  {
    adult: false,
    backdrop_path: '/3GW0A72MxsSgghqpjc2O2MvO8Ec.jpg',
    genre_ids: [27, 35],
    id: 714277,
    original_language: 'es',
    original_title: 'La Funeraria',
    overview:
      'Bernardo is an undertaker. He runs his mortuary business in the same house where he resides. In the front, he has his clients. And in the back, his dysfunctional family lives amongst coffins, wreaths, and the mischievous but nonviolent ghosts that visit on a daily basis. But when a malevolent entity enters the scene, it wreaks havoc on the already fractured household.',
    popularity: 345.6,
    poster_path: '/1rlgIzw129hEl46bFaJZ7wpEEZZ.jpg',
    release_date: '2021-04-15',
    title: 'The Funeral Home',
    video: false,
    vote_average: 1.3,
    vote_count: 3,
  },
  {
    adult: false,
    backdrop_path: '/sNKnz0ZU8u55yCFreZUSOIBMSuY.jpg',
    genre_ids: [35, 10751],
    id: 638597,
    original_language: 'en',
    original_title: 'Yes Day',
    overview:
      "A mom and dad who usually say no decide to say yes to their kids' wildest requests — with a few ground rules — on a whirlwind day of fun and adventure.",
    popularity: 277.767,
    poster_path: '/rejrD9ovTHJbfmpLM0mbEliEPV6.jpg',
    release_date: '2021-03-12',
    title: 'Yes Day',
    video: false,
    vote_average: 7,
    vote_count: 486,
  },
  {
    adult: false,
    backdrop_path: '/ne4QPHn56Z1vxk6iKJKvDnmNI9Y.jpg',
    genre_ids: [28, 80, 18, 53],
    id: 611914,
    original_language: 'en',
    original_title: 'The Courier',
    overview:
      'This intense action-thriller unfolds in real time as two embattled souls fight for their lives. Gary Oldman stars as a vicious crime boss out to kill Nick, the lone witness set to testify against him. He hires a mysterious female motorcycle courier to unknowingly deliver a poison-gas bomb to slay Nick, but after she rescues Nick from certain death, the duo must confront an army of ruthless hired killers in order to survive the night.',
    popularity: 240.706,
    poster_path: '/cmC7bJZ5sCzx9ZsrlXOrYJfYtLc.jpg',
    release_date: '2019-11-22',
    title: 'The Courier',
    video: false,
    vote_average: 6.3,
    vote_count: 354,
  },
  {
    adult: false,
    backdrop_path: '/4br4B8C0SRIYcKHUgoaOlGo50MU.jpg',
    genre_ids: [27],
    id: 575088,
    original_language: 'ru',
    original_title: 'Яга. Кошмар тёмного леса',
    overview:
      'The young family who moved to a new apartment on the outskirts of the city. The nanny hired by them for the newborn daughter quickly gained confidence. However, the older boy, Egor, talks about the frightening behavior of a woman, but his parents do not believe him. The surveillance cameras installed by the father for comfort only confirm everything is in order. Then one day, Egor, returning home, finds no trace of either the nanny or the little sister, and the parents are in a strange trance and do not even remember that they had a daughter. Then Egor, together with his friends, goes in search, during which it turns out that the nanny is an ancient Slavic demon, popularly known as Baba Yaga.',
    popularity: 227.139,
    poster_path: '/8m5HTXzwewlfXhtZtLlLts53YTW.jpg',
    release_date: '2020-02-27',
    title: 'Baba Yaga: Terror of the Dark Forest',
    video: false,
    vote_average: 6.2,
    vote_count: 120,
  },
  {
    adult: false,
    backdrop_path: '/mvxR0mbDVQkQp3K1OhEU9iDbGcA.jpg',
    genre_ids: [35],
    id: 595813,
    original_language: 'en',
    original_title: 'Barb and Star Go to Vista Del Mar',
    overview:
      'The story of best friends Barb and Star, who leave their small midwestern town for the first time to go on vacation in Vista Del Mar, Florida, where they soon find themselves tangled up in adventure, love, and a villain’s evil plot to kill everyone in town.',
    popularity: 214.092,
    poster_path: '/8oiV8GtBG7GDJa3ejvxZzJnBgff.jpg',
    release_date: '2021-03-29',
    title: 'Barb and Star Go to Vista Del Mar',
    video: false,
    vote_average: 6.3,
    vote_count: 19,
  },
  {
    adult: false,
    backdrop_path: '/bjjZXrP8PEdFeJkKERc62xlarMI.jpg',
    genre_ids: [18, 37],
    id: 581734,
    original_language: 'en',
    original_title: 'Nomadland',
    overview:
      'A woman in her sixties embarks on a journey through the western United States after losing everything in the Great Recession, living as a van-dwelling modern-day nomad.',
    popularity: 200.06,
    poster_path: '/66GUmWpTHgAjyp4aBSXy63PZTiC.jpg',
    release_date: '2021-01-29',
    title: 'Nomadland',
    video: false,
    vote_average: 7.5,
    vote_count: 562,
  },
  {
    adult: false,
    backdrop_path: '/aHYUj0hICtWZ5tPiCIm6pWUcjYK.jpg',
    genre_ids: [27, 28, 18, 10752],
    id: 675327,
    original_language: 'en',
    original_title: 'Shadow in the Cloud',
    overview:
      'A WWII pilot traveling with top secret documents on a B-17 Flying Fortress encounters an evil presence on board the flight.',
    popularity: 191.549,
    poster_path: '/t7EUMSlfUN3jUSZUJOLURAzJzZs.jpg',
    release_date: '2020-12-31',
    title: 'Shadow in the Cloud',
    video: false,
    vote_average: 5.8,
    vote_count: 288,
  },
  {
    adult: false,
    backdrop_path: '/xUUtcxWC6H48UCrpRwwSPQz69XC.jpg',
    genre_ids: [53, 27],
    id: 659986,
    original_language: 'en',
    original_title: 'The Owners',
    overview:
      'A group of friends think they found the perfect easy score - an empty house with a safe full of cash. But when the elderly couple that lives there comes home early, the tables are suddenly turned. As a deadly game of cat and mouse ensues, the would-be thieves must fight to save themselves from a nightmare they could never have imagined.',
    popularity: 185.145,
    poster_path: '/gzFatNrw0lhKD5NxaU6zC7S2KjP.jpg',
    release_date: '2020-08-27',
    title: 'The Owners',
    video: false,
    vote_average: 5.8,
    vote_count: 159,
  },
  {
    adult: false,
    backdrop_path: '/vX5JtEcumMQvMCLVcIqfetc7hdg.jpg',
    genre_ids: [35, 80, 53],
    id: 601666,
    original_language: 'en',
    original_title: 'I Care a Lot',
    overview:
      'A court-appointed legal guardian defrauds her older clients and traps them under her care. But her latest mark comes with some unexpected baggage.',
    popularity: 162.118,
    poster_path: '/gKnhEsjNefpKnUdAkn7INzIFLSu.jpg',
    release_date: '2021-02-19',
    title: 'I Care a Lot',
    video: false,
    vote_average: 6.7,
    vote_count: 1249,
  },
  {
    adult: false,
    backdrop_path: '/eLq6NEt3pwLvYrN5C6dPFcaTt7D.jpg',
    genre_ids: [18, 53],
    id: 644583,
    original_language: 'en',
    original_title: 'The Mauritanian',
    overview:
      "A detainee at the U.S military's Guantanamo Bay detention center is held without charges for over a decade and seeks help from a defense attorney for his release.",
    popularity: 160.422,
    poster_path: '/lIADEa6oH74uUapjsPbNRzxus8M.jpg',
    release_date: '2021-02-12',
    title: 'The Mauritanian',
    video: false,
    vote_average: 7.3,
    vote_count: 175,
  },
  {
    adult: false,
    backdrop_path: '/5KmhjlR5CEarB8mKtpjcjHRYIu9.jpg',
    genre_ids: [80, 28, 18],
    id: 535292,
    original_language: 'en',
    original_title: '21 Bridges',
    overview:
      'An embattled NYPD detective, is thrust into a citywide manhunt for a pair of cop killers after uncovering a massive and unexpected conspiracy. As the night unfolds, lines become blurred on who he is pursuing, and who is in pursuit of him.',
    popularity: 142.585,
    poster_path: '/bSN9SysoRBMwJKNkfOlQlCw2YQO.jpg',
    release_date: '2019-10-24',
    title: '21 Bridges',
    video: false,
    vote_average: 6.8,
    vote_count: 1240,
  },
  {
    adult: false,
    backdrop_path: '/4JeO6EeNOnWpzgay99EicUoRdIP.jpg',
    genre_ids: [80, 53, 18],
    id: 579051,
    original_language: 'en',
    original_title: 'Silk Road',
    overview:
      'The true story of Ross Ulbricht, the charismatic young tech-mastermind who unleashed the darknet website Silk Road, and the corrupt DEA agent determined to bring down his billion-dollar empire.',
    popularity: 140.389,
    poster_path: '/6KxiEWyIDpz1ikmD7nv3GTX4Uoj.jpg',
    release_date: '2021-02-19',
    title: 'Silk Road',
    video: false,
    vote_average: 6.9,
    vote_count: 39,
  },
  {
    adult: false,
    backdrop_path: '/3pIqd1hgZ2xqzWEyiYp4blqE9Fi.jpg',
    genre_ids: [18, 53],
    id: 522241,
    original_language: 'en',
    original_title: 'The Courier',
    overview:
      'Cold War spy Greville Wynne and his Russian source try to put an end to the Cuban Missile Crisis.',
    popularity: 127.621,
    poster_path: '/zFIjKtZrzhmc7HecdFXXjsLR2Ig.jpg',
    release_date: '2021-03-18',
    title: 'The Courier',
    video: false,
    vote_average: 6.3,
    vote_count: 22,
  },
  {
    adult: false,
    backdrop_path: '/h3weAFgg06GqchI2xDfufBgSFTj.jpg',
    genre_ids: [18],
    id: 600354,
    original_language: 'en',
    original_title: 'The Father',
    overview:
      'A man refuses all assistance from his daughter as he ages and, as he tries to make sense of his changing circumstances, he begins to doubt his loved ones, his own mind and even the fabric of his reality.',
    popularity: 127.41,
    poster_path: '/uxWXW1YYQENSv7OzHB4Hds0bK3b.jpg',
    release_date: '2020-12-23',
    title: 'The Father',
    video: false,
    vote_average: 8.3,
    vote_count: 376,
  },
  {
    adult: false,
    backdrop_path: '/rWrvcsrvISKXdMOzCdkvU3Jtg0j.jpg',
    genre_ids: [53, 80, 18],
    id: 582014,
    original_language: 'en',
    original_title: 'Promising Young Woman',
    overview:
      'A young woman, traumatized by a tragic event in her past, seeks out vengeance against those who crossed her path.',
    popularity: 125.156,
    poster_path: '/cjzU4g6SlScnP4MdkleyI25KGlR.jpg',
    release_date: '2020-12-13',
    title: 'Promising Young Woman',
    video: false,
    vote_average: 7.6,
    vote_count: 736,
  },
  {
    adult: false,
    backdrop_path: '/8f9dnOtpArDrOMEylpSN9Sc6fuz.jpg',
    genre_ids: [12, 14, 10751],
    id: 674,
    original_language: 'en',
    original_title: 'Harry Potter and the Goblet of Fire',
    overview:
      "When Harry Potter's name emerges from the Goblet of Fire, he becomes a competitor in a grueling battle for glory among three wizarding schools — the Triwizard Tournament. But since Harry never submitted his name for the Tournament, who did? Now Harry must confront a deadly dragon, fierce water demons and an enchanted maze only to find himself in the cruel grasp of He Who Must Not Be Named. In this fourth film adaptation of J.K. Rowling's Harry Potter series, everything changes as Harry, Ron and Hermione leave childhood forever and take on challenges greater than anything they could have imagined.",
    popularity: 120.617,
    poster_path: '/fECBtHlr0RB3foNHDiCBXeg9Bv9.jpg',
    release_date: '2005-11-16',
    title: 'Harry Potter and the Goblet of Fire',
    video: false,
    vote_average: 7.8,
    vote_count: 15395,
  },
  {
    adult: false,
    backdrop_path: '/DnjwdbjdR2c5MFhKv5ZSRf8rDU.jpg',
    genre_ids: [53, 27, 18],
    id: 546121,
    original_language: 'en',
    original_title: 'Run',
    overview:
      'Chloe, a teenager who is confined to a wheelchair, is homeschooled by her mother, Diane. Chloe soon becomes suspicious of her mother and begins to suspect that she may be harboring a dark secret.',
    popularity: 103.171,
    poster_path: '/ilHG4EayOVoYeKqslspY3pR4wzC.jpg',
    release_date: '2020-11-20',
    title: 'Run',
    video: false,
    vote_average: 7.5,
    vote_count: 816,
  },
  {
    adult: false,
    backdrop_path: '/fatz1aegtBGh7KS0gipcsw9MqUn.jpg',
    genre_ids: [18, 36],
    id: 583406,
    original_language: 'en',
    original_title: 'Judas and the Black Messiah',
    overview:
      "Bill O'Neal infiltrates the Black Panthers on the orders of FBI Agent Mitchell and J. Edgar Hoover. As Black Panther Chairman Fred Hampton ascends—falling for a fellow revolutionary en route—a battle wages for O’Neal’s soul.",
    popularity: 99.794,
    poster_path: '/iIgr75GoqFxe1X5Wz9siOODGe9u.jpg',
    release_date: '2021-02-12',
    title: 'Judas and the Black Messiah',
    video: false,
    vote_average: 7.5,
    vote_count: 404,
  },
];
